@cohort @regression
Feature: Cohort Management — Super Admin
  As a Super Admin
  I want to manage cohorts from the Cohort Management page
  So that I can create, search, filter, and edit cohorts

  # All login credentials are read from LoginData.xlsx via TestDataProvider.
  # All search/filter/create test data is read from CohortManagementTestData.xlsx
  # via CohortTestData — zero hardcoded values in this feature file.
  Background:
    Given I am on the login page
    When I login with credentials for "Super Admin"
    And I navigate to Cohort Management
    Then the cohort management page should load successfully

  # ── TC-COHORT-001 ──────────────────────────────────────────────────────────
  # Verifies that the Super Admin → Cohort Management navigation lands on the
  # correct URL and displays the expected page heading.
  @smoke
  Scenario: TC-COHORT-001 Page loads with correct URL and heading
    Then the URL should contain "cohort"
    And the cohort page heading should contain "Cohort Management"

  # ── TC-COHORT-002 ──────────────────────────────────────────────────────────
  # Verifies that all business-required columns are present in the table.
  # Column names are compared case-insensitively via AppConstants.COHORT_COL_*.
  Scenario: TC-COHORT-002 Cohort table has all required column headers
    Then the cohort table should have all required column headers

  # ── TC-COHORT-003 ──────────────────────────────────────────────────────────
  # Verifies the table is populated and the loaded row count matches the
  # total-records counter shown in the UI.
  @smoke
  Scenario: TC-COHORT-003 Cohort table has at least one data row
    Then the cohort table should have at least one data row
    And the loaded row count should not exceed the total record count

  # ── TC-COHORT-004 ──────────────────────────────────────────────────────────
  # Verifies the search bar filters the list.
  # Strategy: uses the actual first row's Cohort ID as the search term so the
  # test is data-independent (no hardcoded cohort ID in the feature file).
  Scenario: TC-COHORT-004 Search bar filters the cohort list
    When I search the cohort list using the first visible cohort ID
    Then the filtered row count should be less than the unfiltered list
    And the first search result should contain the cohort ID that was searched

  # ── TC-COHORT-005 ──────────────────────────────────────────────────────────
  # Negative search: keywords from the SearchCohort sheet with ExpectedMinRows=0
  # must return zero rows. The step iterates all negative scenarios from Excel.
  Scenario: TC-COHORT-005 Non-matching search keywords return zero results
    When I perform each negative search scenario from the test data
    Then each non-matching search should return zero cohort rows

  # ── TC-COHORT-006 ──────────────────────────────────────────────────────────
  # Verifies that the Create New Cohort button opens the creation modal.
  @smoke
  Scenario: TC-COHORT-006 Create New Cohort button opens a modal
    When I click Create New Cohort
    Then the cohort creation modal should be visible
    And the modal title should not be empty

  # ── TC-COHORT-007 ──────────────────────────────────────────────────────────
  # Verifies modal form structure: exactly 2 date inputs, no free-text inputs
  # (cohort ID and name are auto-generated by the backend — FR-017).
  Scenario: TC-COHORT-007 Create modal has exactly 2 date inputs and no free-text inputs
    When I click Create New Cohort
    Then the create cohort modal should have exactly 2 date input fields
    And the create cohort modal should have no free-text input fields

  # ── TC-COHORT-008 ──────────────────────────────────────────────────────────
  # Verifies that the pencil-icon Edit button in the Actions column opens the
  # edit modal with form fields pre-populated.
  Scenario: TC-COHORT-008 Edit button opens the edit modal
    When I click the first Edit button in the cohort table
    Then the cohort edit modal should be visible

  # ── TC-COHORT-009 ──────────────────────────────────────────────────────────
  # Verifies that clicking the Cohort ID link navigates to the detail page.
  Scenario: TC-COHORT-009 Clicking a Cohort ID navigates to the detail page
    When I click the first Cohort ID link in the cohort table
    Then the URL should change to the cohort detail page
    And the cohort management page should be accessible after navigating back

  # ── TC-COHORT-010 ──────────────────────────────────────────────────────────
  # Verifies the Filters button reveals the inline filter panel.
  Scenario: TC-COHORT-010 Filters button opens an inline filter panel
    When I click the Filters button on the cohort page
    Then the filter panel should reveal at least one dropdown

  # ── TC-COHORT-011 ──────────────────────────────────────────────────────────
  # Verifies filter dropdown options against the FilterStatus Excel sheet.
  # Expected status values (ShouldExistInDropdown=YES) are read from Excel —
  # no status strings are hardcoded in this file.
  Scenario: TC-COHORT-011 Filter panel dropdowns contain the expected values
    When I click the Filters button on the cohort page
    Then the Status filter dropdown should contain all expected values from the test data
    And the Learning Path filter should have at least one option

  # ── TC-COHORT-012 ──────────────────────────────────────────────────────────
  # Verifies that status badges are rendered with known status values.
  Scenario: TC-COHORT-012 Status badges show valid status values
    Then status badges should be visible in the cohort table
    And at least one badge should display a known status value

  # ── TC-COHORT-013 ──────────────────────────────────────────────────────────
  # Verifies the Create New Cohort button is not disabled.
  @smoke
  Scenario: TC-COHORT-013 Create New Cohort button is enabled
    Then the Create New Cohort button should be enabled

  # ── TC-COHORT-014 ──────────────────────────────────────────────────────────
  # Verifies the Cancel button dismisses the modal without navigating away.
  Scenario: TC-COHORT-014 Cancel button closes the Create Cohort modal
    When I click Create New Cohort
    And I click the Cancel button in the modal
    Then the cohort creation modal should be closed

  # ── TC-COHORT-015 — BUG REGRESSION ────────────────────────────────────────
  # The application currently accepts cohort creation even when the End Date is
  # before the Start Date, producing a "Success" alert. This is a confirmed bug.
  #
  # Expected behaviour: form should block submission and show a validation error.
  # Tag @known-issue so CI pipelines can run --tags "not @known-issue" to skip
  # this test until the bug is fixed, then remove the tag once the fix ships.
  @bug @known-issue
  Scenario: TC-COHORT-015 [BUG] End date before start date should be rejected
    When I click Create New Cohort
    And I fill the cohort form with the default happy path scenario data
    And I set the end date to before the start date
    And I submit the cohort creation form
    Then the cohort creation should not have succeeded with a success alert
    And the cohort creation modal should still be visible

  # ── TC-COHORT-016 — BUG REGRESSION ────────────────────────────────────────
  # Service lines that have no associated learning path IDs appear in the Service
  # Line dropdown but cause a "400 BAD_REQUEST: Invalid Learning Path ID" error
  # when the form is submitted. Bug service lines are read from the BUG_SL rows
  # in the CreateCohort Excel sheet — none are hardcoded here.
  @bug @known-issue
  Scenario: TC-COHORT-016 [BUG] Service lines without learning paths should not be selectable
    When I check each bug service line scenario from the test data
    Then each checked service line should have no available learning path options

  # ── TC-COHORT-017 ──────────────────────────────────────────────────────────
  # Happy path: creates a cohort with fully valid data (from HAPPY_PATH row in
  # CreateCohort sheet), verifies the success alert, and confirms the new row
  # appears in the table.
  @smoke
  Scenario: TC-COHORT-017 Successfully create a new cohort with valid data
    Given I note the current cohort row count
    When I click Create New Cohort
    And I fill the cohort form with the default happy path scenario data
    And I set valid future start and end dates
    And I submit the cohort creation form
    Then the cohort creation should succeed
    And the cohort table should have at least one more row than before
